logged in user can now create a new product to sell
nss-ivory-trolls/BangazonSite pull request #33
Opened 2019-04-22 20:02 UTC by colebryant

# Description

Added controller methods and views which enable the user to enter a new product to sell.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Testing Instructions for Change Made

1. `git fetch -a`
1. `git checkout cb-products-add`
1. Run Bangazon
1. Verify that only when the user is logged in, they can access the create product view. 
1. Verify that a new product can be created, and that there is form validation for all the fields (except for city and image path).
1. Verify that once a new product is created, the user is redirected to the details view for that product.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [ ] I have added test instructions that prove my fix is effective or that my feature works

2019-04-22 21:30 UTC, THATBLADEBOY approved these changes
Works as described 👍

2019-04-22 21:34 UTC, jdbbaugh approved these changes
Solid, may need to take out userId in the long run but works as described 🤘

2019-04-23 15:07 UTC, dakotacookson approved these changes
All good in the hood

2019-04-23 15:13 UTC, askingalot requested changes

2019-04-23 15:13 UTC, askingalot commented on Bangazon/Models/Product.cs
>      public string UserId {get; set;}
UserId should be required

2019-04-23 15:13 UTC, askingalot commented on Bangazon/Controllers/ProductsController.cs
> +            ViewData["ProductTypeId"] = new SelectList(_context.ProductType, "Value", "Text", product.ProductTypeId);
ViewModel

2019-04-23 15:13 UTC, askingalot commented on Bangazon/Controllers/ProductsController.cs
> +            var errors = ModelState.Values.SelectMany(v => v.Errors);
What is this for?

2019-04-23 17:05 UTC, askingalot approved these changes

2019-04-23 17:54 UTC, merged