Jb tues ticket8
nss-ivory-trolls/BangazonSite pull request #36
Opened 2019-04-23 10:27 UTC by jdbbaugh

## Ticket #1 

Given a user is viewing any page on the Bangazon site
When the user performs a gesture on the Product Categories hyperlink
Then the user will see a view containing a list of all product categories
And next to the category name, the number of products in that category will be displayed
And the first three products in the category will be displayed beneath each category, that are hyperlinks to the product detail

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions for Change Made

1.  `git fetch --all`
1.  `git checkout jb-monTicket1`
1.  run Bangazon
1.  in nav bar click "Products"  (don't use dropdown)
1.  you will see product types displayed along with amount of that particular product type available
1.  if particular product type doesn't have product in it, you will not see that product type listed
1.  product types will list no more then 3 of it's available products
1.  now click an available product under any of the Product Types (like "kite")
1.  you will now see a detailed description of the kite (Note: Add to order button does not work)
1.  in detailed description "back to list" hyperlink will return you to product type list you came from

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

2019-04-23 14:13 UTC, THATBLADEBOY approved these changes
Works as described 👍

2019-04-23 14:57 UTC, colebryant approved these changes
Looks good

2019-04-23 15:01 UTC, dakotacookson approved these changes
Lovley

2019-04-23 15:35 UTC, askingalot requested changes
clean up specific category views/methods.

2019-04-24 15:17 UTC, askingalot requested changes

2019-04-24 15:17 UTC, askingalot commented on Bangazon/Controllers/OrdersController.cs
> +            ViewData["PaymentTypeId"] = new SelectList(_context.PaymentType.Where(p => p.UserId == user.Id), "PaymentTypeId", "PaymentMethod");
Use a view model

2019-04-24 15:17 UTC, askingalot commented on Bangazon/Views/Orders/Cart.cshtml
> +                    <input type="button" value="Delete Order" class="btn btn-danger"
this is clever, but use an HTML `form`

2019-04-24 19:44 UTC, closed without merging